### ISSUE TITLE
Discord Invite Not Working

### ISSUE THREAD

**Issue by h3farooqi** [KevinEdry/runelite-quest-voiceover#3]
@KevinEdry Idk if I'm just an idiot, but your discord invite is a straight png.
Just needed to find a way to contact you and say this.

**Comment by KevinEdry** [comment]
@h3farooqi thats odd, let me fix that.

**Comment by ctdgunner** [comment]
same thing for me actually when clicking the discord here https://runelite.net/plugin-hub/show/quest-voiceover

**Comment by KevinEdry** [comment]
fixed in here, its now pending release.
